"""
Django settings for ridebuddies project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Einstellungen fuer den Betrieb kommen aus der Umgebung, nie aus dem Repo.
# Auf dem Server setzt sie die systemd-Unit aus einer EnvironmentFile ausserhalb
# von Git. Ohne RIDEBUDDIES_DEBUG=1 laeuft die Anwendung im Betriebsmodus und
# verweigert den Start ohne eigenen SECRET_KEY.
# https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

DEBUG = os.environ.get('RIDEBUDDIES_DEBUG') == '1'

SECRET_KEY = os.environ.get('RIDEBUDDIES_SECRET_KEY', '')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured('RIDEBUDDIES_SECRET_KEY fehlt (oder RIDEBUDDIES_DEBUG=1 setzen).')
    SECRET_KEY = 'django-insecure-nur-fuer-die-lokale-entwicklung'

ALLOWED_HOSTS = [h for h in os.environ.get('RIDEBUDDIES_ALLOWED_HOSTS', '').split(',') if h]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']

# Datenbank und gesammelte statische Dateien liegen im Betrieb ausserhalb des Klons,
# getrennt, damit nginx die statischen Dateien lesen kann, die Datenbank aber nicht.
DATA_DIR = Path(os.environ.get('RIDEBUDDIES_DATA_DIR', BASE_DIR))

if not DEBUG:
    # nginx terminiert TLS und reicht das Schema im Kopf X-Forwarded-Proto weiter.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    CSRF_TRUSTED_ORIGINS = [f'https://{h}' for h in ALLOWED_HOSTS]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'allauth',
    'allauth.account',
    'kern',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Anmeldepflicht global (Fabian, 23.09.2026): ohne Anmeldung leitet jede
    # Seite auf LOGIN_URL um. Ausgenommen ist nur, was mit login_not_required
    # markiert ist - die allauth-Konto-Views (Login, Registrierung,
    # Passwort vergessen, Bestaetigungslink) tun das selbst, ebenso die
    # Umleitung unter /admin/login/ auf /konto/login/ (kern/views.py; Djangos
    # eigenes Admin-Formular ist seit TASK-120.10 nicht mehr erreichbar).
    # Unbekannte Pfade loesen nicht auf und enden als 404, ohne etwas zu
    # zeigen. Belegt in ridebuddies/tests.py und kern/tests/test_anmeldung.py.
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'ridebuddies.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ridebuddies.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATA_DIR / 'db.sqlite3',
    }
}


# Nutzer und Anmeldung
# Eigenes Nutzermodell von Anfang an (Fabian, 23.09.2026). Deshalb beginnen die
# Migrationen mit TASK-120.04 neu; eine Datenbank aus Schritt 3b (mit Djangos
# auth_user) passt nicht mehr und wird neu angelegt.

AUTH_USER_MODEL = 'kern.Nutzer'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_URL = 'account_login'
LOGIN_REDIRECT_URL = 'startseite'

# django-allauth: Anmelden mit Nutzername oder E-Mail, E-Mail-Bestaetigung
# Pflicht. Oberflaeche und Onboarding kommen erst in Schritt 11; bis dahin
# genuegen die allauth-Standardvorlagen.
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_ADAPTER = 'kern.adapter.KontoAdapter'

# Client-IP hinter nginx (Hotfix 23.09.2026). Auf enduro-web scheiterte JEDE
# Anmeldung ueber /konto/login/ mit einem nackten 403, auch mit unbekanntem
# Nutzernamen: gunicorn lauscht auf einem Unix-Socket
# (unix:/run/ridebuddies/gunicorn.sock), REMOTE_ADDR ist dort leer. allauth
# braucht die Client-IP fuer seine Ratenbegrenzung
# (allauth/core/internal/httpkit.py get_client_ip) und wirft PermissionDenied,
# wenn es keine findet. Der Django-Testclient setzt REMOTE_ADDR=127.0.0.1 und
# hat den Fehler deshalb nie gesehen.
#
# nginx setzt X-Forwarded-For mit $proxy_add_x_forwarded_for, haengt die echte
# Gegenstelle also RECHTS an. Genau ein vertrauenswuerdiger Proxy -> allauth
# nimmt ips[-1]. Was der Client links voranstellt, wird ignoriert; ein
# groesserer Wert waere ein Loch, weil dann ein vorgetaeuschter Eintrag zaehlt.
# Ohne X-Forwarded-For (runserver, Tests) faellt allauth auf REMOTE_ADDR
# zurueck; ohne beides bleibt das 403 (kern/tests/test_anmeldung.py).
ALLAUTH_TRUSTED_PROXY_COUNT = 1

# Registrierung zu, solange nur Dummies laufen und keine Mail rausgeht
# (Festlegung der Hauptsitzung, siehe kern/adapter.py). Auf mit =1.
RIDEBUDDIES_REGISTRIERUNG_OFFEN = os.environ.get('RIDEBUDDIES_REGISTRIERUNG_OFFEN') == '1'


# KI-Urteile fuers Matching (Karte TASK-120.12, Paket kern/urteile/).
# Welcher Anbieter antwortet: jev | claude | test. Voreinstellung test - der
# antwortet ohne Netz neutral bzw. aus einer Aufzeichnung, damit weder ein
# vergessener Schalter noch ein Testlauf Daten an einen US-Dienst schickt.
# Festlegung (nicht von Fabian entschieden).
RIDEBUDDIES_KI_ANBIETER = os.environ.get('RIDEBUDDIES_KI_ANBIETER', 'test').strip() or 'test'
if RIDEBUDDIES_KI_ANBIETER not in ('jev', 'claude', 'test'):
    raise ImproperlyConfigured('RIDEBUDDIES_KI_ANBIETER muss jev, claude oder test sein.')


def _ki_freigabe(roh):
    """RIDEBUDDIES_KI_FREIGABE = 'nutzername:email' -> (nutzername, email_klein)
    oder None, wenn leer.

    Entscheidung Fabians (23.09.2026): Sein eigenes Konto darf an die
    KI-Anbieter und wird hier benannt, GENAU EIN Konto im Format
    nutzername:email; Nutzername UND E-Mail muessen beide passen. Nicht gesetzt
    = nur Dummies (kern/urteile/sperre.py).
    Festlegung (nicht von Fabian entschieden): E-Mail ohne Gross/Klein; ein
    Komma (= Versuch, mehrere Konten freizugeben) oder ein kaputter Eintrag
    bricht den Start ab, statt still niemanden oder den Falschen freizugeben.
    Die Meldung nennt den Wert NICHT - er ist eine E-Mail-Adresse und landete
    sonst im Journal."""
    roh = roh.strip()
    if not roh:
        return None
    if ',' in roh:
        raise ImproperlyConfigured('RIDEBUDDIES_KI_FREIGABE nimmt genau ein Konto '
                                   '(nutzername:email), keine Liste.')
    name, _, email = roh.partition(':')
    name, email = name.strip(), email.strip().lower()
    if not name or '@' not in email or ':' in email:
        raise ImproperlyConfigured('RIDEBUDDIES_KI_FREIGABE braucht die Form nutzername:email.')
    return (name, email)


RIDEBUDDIES_KI_FREIGABE = _ki_freigabe(os.environ.get('RIDEBUDDIES_KI_FREIGABE', ''))

# Modelle. Jev meldet in der Antwort die tatsaechliche Version (jev-1.13.0 ...),
# die steht dann im Urteil; hier steht nur, was angefragt wird.
RIDEBUDDIES_JEV_MODELL = os.environ.get('RIDEBUDDIES_JEV_MODELL', 'jev-latest')
RIDEBUDDIES_CLAUDE_MODELL = os.environ.get('RIDEBUDDIES_CLAUDE_MODELL', 'claude-haiku-4-5')
# Zeitlimit je HTTP-Versuch in Sekunden (Wiederholungen: kern/urteile/netz.py).
def _ki_zeitlimit(roh):
    """Sekunden, ueber 0 und hoechstens 600 (Festlegung) - sonst bricht der Start
    ab wie bei den Nachbarn, statt spaeter an einem Zeitlimit 'abc' zu scheitern."""
    try:
        wert = float(roh)
    except ValueError:
        wert = 0.0
    if not 0 < wert <= 600:   # auch nan und inf fallen hier durch
        raise ImproperlyConfigured('RIDEBUDDIES_KI_ZEITLIMIT muss eine Zahl von Sekunden '
                                   'über 0 und höchstens 600 sein.')
    return wert


RIDEBUDDIES_KI_ZEITLIMIT = _ki_zeitlimit(os.environ.get('RIDEBUDDIES_KI_ZEITLIMIT', '30'))
# Test-Anbieter: Aufzeichnung, aus der er antwortet (JSON, siehe
# kern/urteile/aufzeichnung.py). Leer = neutrale Antworten.
RIDEBUDDIES_KI_AUFZEICHNUNG = os.environ.get('RIDEBUDDIES_KI_AUFZEICHNUNG', '')
# Echte Anbieter: jede Antwort zusaetzlich in diese Datei mitschneiden (ohne
# Zustand, Fragetext und Schluessel). Leer = kein Mitschnitt.
RIDEBUDDIES_KI_MITSCHNITT = os.environ.get('RIDEBUDDIES_KI_MITSCHNITT', '')
# Die API-Schluessel stehen absichtlich NICHT hier: RIDEBUDDIES_JEV_SCHLUESSEL
# und RIDEBUDDIES_ANTHROPIC_SCHLUESSEL (oder je *_DATEI) liest
# kern/urteile/anbieter.py erst beim Aufruf aus der Umgebung. Djangos
# Fehlerseite blendet nur Einstellungen mit KEY/SECRET/TOKEN/... im Namen aus,
# "SCHLUESSEL" stuende dort im Klartext.

# Protokoll der KI-Urteile ins Journal (Entscheidung Fabians, 24.09.2026).
# Der Logger ridebuddies.urteile schreibt ab INFO auf stderr; die systemd-Unit
# reicht stderr an journald weiter (journalctl -u ridebuddies.service), lokal steht es
# im Terminal. Inhalt nur Anbieter, Modell, Kennung, Form, Dauer, Tokens,
# Anzahl der Betroffenen und Fehlerart - nie Personendaten (kern/urteile/
# __init__.py, belegt in kern/tests/test_urteile.py).
# propagate=False, damit eine spaetere Wurzel-Konfiguration die Zeilen nicht
# doppelt oder anderswohin schreibt; disable_existing_loggers=False und nur
# dieser eine Logger, damit Djangos eigene Protokollierung bleibt, wie sie ist.
# Ohne diesen Block gingen INFO-Zeilen ("urteil ok") nirgendwohin und nur
# WARNING ueber Pythons lastResort auf stderr (Stand vor dem 24.09.2026).
# Kein Zeitstempel im Format: den setzt journald.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'journal': {'format': '%(levelname)s %(name)s %(message)s'},
    },
    'handlers': {
        'ki_journal': {'class': 'logging.StreamHandler', 'formatter': 'journal'},
    },
    'loggers': {
        'ridebuddies.urteile': {'handlers': ['ki_journal'], 'level': 'INFO',
                                'propagate': False},
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'de-de'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = Path(os.environ.get('RIDEBUDDIES_STATIC_ROOT', DATA_DIR / 'static'))


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Bleibt Konsole, bis der E-Mail-Versand entschieden ist (offener Punkt in der
# Plan-Notiz). allauth schickt Bestaetigungsmails also nur ins Log.
DEFAULT_FROM_EMAIL = 'Ridebuddies <noreply@ridebuddies.de>'

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
