"""
Django settings for ridebuddies project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Einstellungen fuer den Betrieb kommen aus der Umgebung, nie aus dem Repo.
# Auf dem Server setzt sie die systemd-Unit aus einer EnvironmentFile ausserhalb
# von Git. Ohne RIDEBUDDIES_DEBUG=1 laeuft die Anwendung im Betriebsmodus und
# verweigert den Start ohne eigenen SECRET_KEY.
# https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

DEBUG = os.environ.get('RIDEBUDDIES_DEBUG') == '1'

SECRET_KEY = os.environ.get('RIDEBUDDIES_SECRET_KEY', '')
if not SECRET_KEY:
    if not DEBUG:
        raise ImproperlyConfigured('RIDEBUDDIES_SECRET_KEY fehlt (oder RIDEBUDDIES_DEBUG=1 setzen).')
    SECRET_KEY = 'django-insecure-nur-fuer-die-lokale-entwicklung'

ALLOWED_HOSTS = [h for h in os.environ.get('RIDEBUDDIES_ALLOWED_HOSTS', '').split(',') if h]
if DEBUG and not ALLOWED_HOSTS:
    ALLOWED_HOSTS = ['localhost', '127.0.0.1', '[::1]']

# Datenbank und gesammelte statische Dateien liegen im Betrieb ausserhalb des Klons,
# getrennt, damit nginx die statischen Dateien lesen kann, die Datenbank aber nicht.
DATA_DIR = Path(os.environ.get('RIDEBUDDIES_DATA_DIR', BASE_DIR))

if not DEBUG:
    # nginx terminiert TLS und reicht das Schema im Kopf X-Forwarded-Proto weiter.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    CSRF_TRUSTED_ORIGINS = [f'https://{h}' for h in ALLOWED_HOSTS]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'allauth',
    'allauth.account',
    'kern',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Anmeldepflicht global (Fabian, 23.09.2026): ohne Anmeldung leitet jede
    # Seite auf LOGIN_URL um. Ausgenommen ist nur, was mit login_not_required
    # markiert ist - die allauth-Konto-Views (Login, Registrierung,
    # Passwort vergessen, Bestaetigungslink) tun das selbst, ebenso Djangos
    # Admin-Login. Unbekannte Pfade loesen nicht auf und enden als 404, ohne
    # etwas zu zeigen. Belegt in ridebuddies/tests.py.
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
]

ROOT_URLCONF = 'ridebuddies.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ridebuddies.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': DATA_DIR / 'db.sqlite3',
    }
}


# Nutzer und Anmeldung
# Eigenes Nutzermodell von Anfang an (Fabian, 23.09.2026). Deshalb beginnen die
# Migrationen mit TASK-120.04 neu; eine Datenbank aus Schritt 3b (mit Djangos
# auth_user) passt nicht mehr und wird neu angelegt.

AUTH_USER_MODEL = 'kern.Nutzer'

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_URL = 'account_login'
LOGIN_REDIRECT_URL = 'startseite'

# django-allauth: Anmelden mit Nutzername oder E-Mail, E-Mail-Bestaetigung
# Pflicht. Oberflaeche und Onboarding kommen erst in Schritt 11; bis dahin
# genuegen die allauth-Standardvorlagen.
ACCOUNT_LOGIN_METHODS = {'username', 'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'username*', 'password1*', 'password2*']
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_UNIQUE_EMAIL = True
ACCOUNT_ADAPTER = 'kern.adapter.KontoAdapter'

# Registrierung zu, solange nur Dummies laufen und keine Mail rausgeht
# (Festlegung der Hauptsitzung, siehe kern/adapter.py). Auf mit =1.
RIDEBUDDIES_REGISTRIERUNG_OFFEN = os.environ.get('RIDEBUDDIES_REGISTRIERUNG_OFFEN') == '1'


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'de-de'

TIME_ZONE = 'Europe/Berlin'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = Path(os.environ.get('RIDEBUDDIES_STATIC_ROOT', DATA_DIR / 'static'))


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

# Bleibt Konsole, bis der E-Mail-Versand entschieden ist (offener Punkt in der
# Plan-Notiz). allauth schickt Bestaetigungsmails also nur ins Log.
DEFAULT_FROM_EMAIL = 'Ridebuddies <noreply@ridebuddies.de>'

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
