# Generated by Django 6.1.1 on 2026-09-23 14:21

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import kern.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('beschreibung', models.TextField(blank=True)),
                ('erstellt', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Crew',
                'verbose_name_plural': 'Crews',
            },
        ),
        migrations.CreateModel(
            name='Nutzer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-Mail-Adresse')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Nutzer',
                'verbose_name_plural': 'Nutzer',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ausfahrt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=150)),
                ('art', models.CharField(choices=[('tagestour', 'Tagestour'), ('reise', 'Reise (mehrtägig)'), ('messe', 'Messe'), ('training', 'Training')], default='tagestour', max_length=12)),
                ('beschreibung', models.TextField(blank=True)),
                ('routenlink', models.URLField(blank=True, help_text='Link auf Stegra/calimoto - keine eigene Routenberechnung')),
                ('status', models.CharField(choices=[('vorgeschlagen', 'vorgeschlagen'), ('abstimmung', 'Abstimmung läuft'), ('fest', 'Termin steht'), ('gefahren', 'gefahren'), ('abgesagt', 'abgesagt')], default='vorgeschlagen', max_length=14)),
                ('erstellt', models.DateTimeField(default=django.utils.timezone.now)),
                ('vorgeschlagen_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ausfahrten', to='kern.crew')),
            ],
            options={
                'verbose_name': 'Ausfahrt/Reise',
                'verbose_name_plural': 'Ausfahrten und Reisen',
            },
        ),
        migrations.CreateModel(
            name='CrewVorschlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('offen', 'offen'), ('angenommen', 'angenommen'), ('verworfen', 'verworfen')], default='offen', max_length=12)),
                ('erstellt', models.DateTimeField(default=django.utils.timezone.now)),
                ('angenommen_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('beteiligte', models.ManyToManyField(related_name='crew_vorschlaege', to=settings.AUTH_USER_MODEL)),
                ('crew', models.ForeignKey(blank=True, help_text='die daraus entstandene Crew', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='kern.crew')),
            ],
            options={
                'verbose_name': 'Crew-Vorschlag',
                'verbose_name_plural': 'Crew-Vorschläge',
            },
        ),
        migrations.CreateModel(
            name='Fremdprofil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dienst', models.CharField(choices=[('stegra', 'Stegra'), ('calimoto', 'calimoto'), ('instagram', 'Instagram'), ('whatsapp', 'WhatsApp'), ('signal', 'Signal'), ('telefon', 'Telefon'), ('mail', 'E-Mail'), ('sonstiges', 'Sonstiges')], max_length=12)),
                ('wert', models.CharField(help_text='Nutzername, Nummer, Adresse oder Link', max_length=200)),
                ('erstellt', models.DateTimeField(default=django.utils.timezone.now)),
                ('inhaber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fremdprofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fremdprofil',
                'verbose_name_plural': 'Fremdprofile',
            },
        ),
        migrations.CreateModel(
            name='Mitgliedschaft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rolle', models.CharField(choices=[('organisator', 'Organisator'), ('mitglied', 'Mitglied'), ('gast', 'Gast')], default='mitglied', max_length=12)),
                ('seit', models.DateTimeField(default=django.utils.timezone.now)),
                ('crew', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitgliedschaften', to='kern.crew')),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mitgliedschaften', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mitgliedschaft',
                'verbose_name_plural': 'Mitgliedschaften',
            },
        ),
        migrations.AddField(
            model_name='crew',
            name='mitglieder',
            field=models.ManyToManyField(related_name='crews', through='kern.Mitgliedschaft', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Nachricht',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('gesendet', models.DateTimeField(default=django.utils.timezone.now)),
                ('gelesen_am', models.DateTimeField(blank=True, null=True)),
                ('absender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nachrichten_gesendet', to=settings.AUTH_USER_MODEL)),
                ('crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nachrichten', to='kern.crew')),
                ('empfaenger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nachrichten_erhalten', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nachricht',
                'verbose_name_plural': 'Nachrichten',
                'ordering': ['gesendet'],
            },
        ),
        migrations.CreateModel(
            name='Profil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altersbereich', models.CharField(blank=True, choices=[('18-24', '18–24'), ('25-34', '25–34'), ('35-44', '35–44'), ('45-54', '45–54'), ('55-64', '55–64'), ('65+', '65 und älter')], max_length=8)),
                ('geschlecht', models.CharField(choices=[('keine_angabe', 'keine Angabe'), ('weiblich', 'weiblich'), ('maennlich', 'männlich'), ('divers', 'divers')], default='keine_angabe', max_length=16)),
                ('region', models.CharField(blank=True, help_text='Ort oder PLZ-Bereich, keine Anschrift.', max_length=100, verbose_name='Region')),
                ('radius_km', models.PositiveSmallIntegerField(default=50, verbose_name='Radius (km)')),
                ('geschlechtspraeferenz', models.CharField(choices=[('gleich', 'gleich'), ('gemischt', 'gemischt'), ('egal', 'egal')], default='egal', max_length=10)),
                ('alterswunsch_von', models.CharField(blank=True, choices=[('18-24', '18–24'), ('25-34', '25–34'), ('35-44', '35–44'), ('45-54', '45–54'), ('55-64', '55–64'), ('65+', '65 und älter')], max_length=8, verbose_name='Altersbereich-Wunsch von')),
                ('alterswunsch_bis', models.CharField(blank=True, choices=[('18-24', '18–24'), ('25-34', '25–34'), ('35-44', '35–44'), ('45-54', '45–54'), ('55-64', '55–64'), ('65+', '65 und älter')], max_length=8, verbose_name='Altersbereich-Wunsch bis')),
                ('fahrarten', models.JSONField(blank=True, default=list, help_text='Mehrfachwahl', validators=[kern.models.fahrarten_pruefen])),
                ('tempo', models.CharField(blank=True, choices=[('gemuetlich', 'gemütlich'), ('zuegig', 'zügig'), ('sportlich', 'sportlich')], max_length=12)),
                ('erfahrung_jahre', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Erfahrung (Jahre)')),
                ('km_pro_jahr', models.PositiveIntegerField(blank=True, null=True, verbose_name='km pro Jahr')),
                ('selbsteinschaetzung', models.CharField(blank=True, choices=[('einsteiger', 'Einsteiger'), ('geuebt', 'geübt'), ('erfahren', 'erfahren'), ('sehr_erfahren', 'sehr erfahren')], max_length=16)),
                ('tourenformate', models.JSONField(blank=True, default=list, help_text='Mehrfachwahl', validators=[kern.models.tourenformate_pruefen])),
                ('tagesdistanz_km', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Tagesdistanz (km)')),
                ('unterwegs_stil', models.CharField(blank=True, choices=[('streckenfresser', 'Streckenfresser'), ('geniesser', 'Genießer'), ('beides', 'mal so, mal so')], max_length=16)),
                ('uebernachtung', models.JSONField(blank=True, default=list, help_text='Mehrfachwahl', validators=[kern.models.uebernachtung_pruefen])),
                ('gruppengroesse', models.CharField(blank=True, choices=[('klein', 'klein (2–3)'), ('mittel', 'mittel (4–6)'), ('gross', 'groß (7+)')], max_length=8)),
                ('themen', models.JSONField(blank=True, default=list, help_text='Mehrfachwahl', validators=[kern.models.themen_pruefen])),
                ('schutzkleidung', models.CharField(blank=True, choices=[('voll', 'volle Schutzkleidung'), ('teilweise', 'teilweise'), ('egal', 'egal')], max_length=10)),
                ('alkohol_auf_tour', models.CharField(blank=True, choices=[('nie', 'nie'), ('nach_der_fahrt', 'erst nach der Fahrt'), ('egal', 'egal')], max_length=16)),
                ('motorrad', models.CharField(blank=True, max_length=100, verbose_name='Motorrad (Typ/Modell)')),
                ('nogo', models.TextField(blank=True, verbose_name='Was ich definitiv nicht möchte')),
                ('feldstufen', models.JSONField(blank=True, default=dict, help_text='Abweichungen von FELD_VOREINSTELLUNG: {feld: 1|2|3}')),
                ('gewichtung', models.JSONField(blank=True, default=dict, help_text='Abweichungen von MERKMAL_VOREINSTELLUNG: {dimension: "hart"|"weich"}')),
                ('geaendert', models.DateTimeField(auto_now=True)),
                ('nutzer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Teilnahme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zusage', models.CharField(choices=[('offen', 'offen'), ('zugesagt', 'zugesagt'), ('abgesagt', 'abgesagt')], default='offen', max_length=10)),
                ('gefahren', models.BooleanField(default=False, help_text='tatsächlich mitgefahren (nach der Ausfahrt)')),
                ('ausfahrt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teilnahmen', to='kern.ausfahrt')),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teilnahmen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teilnahme',
                'verbose_name_plural': 'Teilnahmen',
            },
        ),
        migrations.CreateModel(
            name='Teilung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geteilt_am', models.DateTimeField(default=django.utils.timezone.now)),
                ('empfaenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='erhaltene_teilungen', to=settings.AUTH_USER_MODEL)),
                ('fremdprofil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teilungen', to='kern.fremdprofil')),
            ],
            options={
                'verbose_name': 'Teilung',
                'verbose_name_plural': 'Teilungen',
            },
        ),
        migrations.CreateModel(
            name='Termin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('bis_datum', models.DateField(blank=True, null=True)),
                ('tageszeit', models.CharField(blank=True, choices=[('vormittags', 'vormittags'), ('mittags', 'mittags'), ('nachmittags', 'nachmittags')], max_length=12)),
                ('gewaehlt', models.BooleanField(default=False)),
                ('ausfahrt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='termine', to='kern.ausfahrt')),
            ],
            options={
                'verbose_name': 'Termin',
                'verbose_name_plural': 'Termine',
                'ordering': ['datum', 'tageszeit'],
            },
        ),
        migrations.CreateModel(
            name='Verbindung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('erreicht', models.PositiveSmallIntegerField(choices=[(2, 'verbunden'), (3, 'Ridebuddies')], default=2)),
                ('gewaehrt_a', models.PositiveSmallIntegerField(choices=[(2, 'verbunden'), (3, 'Ridebuddies')], default=2, help_text='bestimmt, was B von A sieht', verbose_name='von A gewährt')),
                ('gewaehrt_b', models.PositiveSmallIntegerField(choices=[(2, 'verbunden'), (3, 'Ridebuddies')], default=2, help_text='bestimmt, was A von B sieht', verbose_name='von B gewährt')),
                ('entstanden_durch', models.CharField(choices=[('vorschlag', 'beidseitig angenommener Vorschlag'), ('anfrage', 'angenommene Anfrage')], max_length=12)),
                ('erstellt', models.DateTimeField(default=django.utils.timezone.now)),
                ('ridebuddies_seit', models.DateTimeField(blank=True, null=True)),
                ('beendet_am', models.DateTimeField(blank=True, null=True)),
                ('beendet_ausgang', models.CharField(blank=True, choices=[('nicht_jetzt', 'nicht jetzt'), ('passt_nicht', 'passt nicht')], max_length=12)),
                ('wiedervorlage_ab', models.DateField(blank=True, null=True)),
                ('beendet_von', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nutzer_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nutzer_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verbindung',
                'verbose_name_plural': 'Verbindungen',
            },
        ),
        migrations.CreateModel(
            name='RidebuddyAnfrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('offen', 'offen'), ('bestaetigt', 'bestätigt'), ('abgelehnt', 'abgelehnt'), ('hinfaellig', 'hinfällig (Verbindung beendet)')], default='offen', max_length=12)),
                ('erstellt', models.DateTimeField(default=django.utils.timezone.now)),
                ('beantwortet_am', models.DateTimeField(blank=True, null=True)),
                ('absender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ridebuddy_anfragen_gesendet', to=settings.AUTH_USER_MODEL)),
                ('empfaenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ridebuddy_anfragen_erhalten', to=settings.AUTH_USER_MODEL)),
                ('verbindung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ridebuddy_anfragen', to='kern.verbindung')),
            ],
            options={
                'verbose_name': 'Ridebuddy-Anfrage',
                'verbose_name_plural': 'Ridebuddy-Anfragen',
            },
        ),
        migrations.CreateModel(
            name='Verfuegbarkeit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('tageszeit', models.CharField(choices=[('vormittags', 'vormittags'), ('mittags', 'mittags'), ('nachmittags', 'nachmittags')], max_length=12)),
                ('stufe', models.CharField(choices=[('sicher', 'sicher'), ('vorbehalt', 'mit Vorbehalt'), ('nein', 'nein')], max_length=10)),
                ('ausfahrt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verfuegbarkeiten', to='kern.ausfahrt')),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verfuegbarkeiten', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verfügbarkeit',
                'verbose_name_plural': 'Verfügbarkeiten',
                'ordering': ['datum', 'tageszeit'],
            },
        ),
        migrations.CreateModel(
            name='Verfuegbarkeitszeitraum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('von', models.DateField()),
                ('bis', models.DateField()),
                ('stufe', models.CharField(choices=[('sicher', 'sicher'), ('vorbehalt', 'mit Vorbehalt'), ('nein', 'nein')], max_length=10)),
                ('ausfahrt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verfuegbarkeitszeitraeume', to='kern.ausfahrt')),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verfuegbarkeitszeitraeume', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Verfügbarkeit (Zeitraum)',
                'verbose_name_plural': 'Verfügbarkeiten (Zeiträume)',
                'ordering': ['von'],
            },
        ),
        migrations.CreateModel(
            name='Vorschlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runde', models.PositiveIntegerField(help_text='Matching-Runde; mehrere Kandidaten je Runde')),
                ('begruendung', models.JSONField(blank=True, default=dict, help_text='{dimension: Begründungstext}')),
                ('reaktion', models.CharField(choices=[('offen', 'offen'), ('angenommen', 'angenommen'), ('nicht_jetzt', 'nicht jetzt'), ('passt_nicht', 'passt nicht')], default='offen', max_length=12)),
                ('reagiert_am', models.DateTimeField(blank=True, null=True)),
                ('wiedervorlage_ab', models.DateField(blank=True, null=True)),
                ('erstellt', models.DateTimeField(default=django.utils.timezone.now)),
                ('empfaenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vorschlaege', to=settings.AUTH_USER_MODEL)),
                ('kandidat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vorschlag',
                'verbose_name_plural': 'Vorschläge',
            },
        ),
        migrations.CreateModel(
            name='Anfrage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('offen', 'offen'), ('angenommen', 'angenommen'), ('abgelehnt', 'abgelehnt')], default='offen', max_length=12)),
                ('erstellt', models.DateTimeField(default=django.utils.timezone.now)),
                ('beantwortet_am', models.DateTimeField(blank=True, null=True)),
                ('absender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anfragen_gesendet', to=settings.AUTH_USER_MODEL)),
                ('empfaenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anfragen_erhalten', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Anfrage',
                'verbose_name_plural': 'Anfragen',
                'constraints': [models.CheckConstraint(condition=models.Q(('absender', models.F('empfaenger')), _negated=True), name='anfrage_nicht_an_sich_selbst'), models.UniqueConstraint(condition=models.Q(('status', 'offen')), fields=('absender', 'empfaenger'), name='anfrage_eine_offene_je_paar')],
            },
        ),
        migrations.CreateModel(
            name='Ausschluss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quelle', models.CharField(choices=[('vorschlag', 'Vorschlag: „passt nicht"'), ('verbindung', 'Verbindung beendet: „passt nicht"'), ('feedback', 'Feedback: „war nix"')], max_length=12)),
                ('grund_dimension', models.CharField(blank=True, choices=[('region', 'Region und Radius'), ('geschlechtspraeferenz', 'Geschlechtspräferenz'), ('alterswunsch', 'Altersbereich-Wunsch'), ('verfuegbarkeit', 'Verfügbarkeit'), ('fahrart', 'Fahrart'), ('tempo', 'Tempo'), ('erfahrung', 'Erfahrung'), ('tourenformat', 'Tourenformat'), ('unterwegs', 'Unterwegs (Streckenfresser/Genießer, Übernachtung, Gruppe)'), ('themen', 'Themen'), ('sicherheit', 'Sicherheit'), ('motorrad', 'Motorrad'), ('nogo', 'No-Go'), ('stimmung', 'Stimmung')], help_text='angetippte Dimension - nur der Urheber sieht sie', max_length=24)),
                ('grund_text', models.TextField(blank=True, help_text='nur der Urheber sieht ihn')),
                ('erstellt', models.DateTimeField(default=django.utils.timezone.now)),
                ('betroffener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('urheber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ausschluesse', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ausschluss',
                'verbose_name_plural': 'Ausschlüsse',
                'constraints': [models.UniqueConstraint(fields=('urheber', 'betroffener'), name='ausschluss_einmal_je_richtung'), models.CheckConstraint(condition=models.Q(('urheber', models.F('betroffener')), _negated=True), name='ausschluss_nicht_sich_selbst')],
            },
        ),
        migrations.CreateModel(
            name='Beitrag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('stufe', models.PositiveSmallIntegerField(choices=[(1, 'öffentlich'), (2, 'verbunden'), (3, 'Ridebuddies')], default=2)),
                ('erstellt', models.DateTimeField(default=django.utils.timezone.now)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beitraege', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Beitrag',
                'verbose_name_plural': 'Beiträge',
                'ordering': ['-erstellt'],
                'constraints': [models.CheckConstraint(condition=models.Q(('stufe__gte', 1), ('stufe__lte', 3)), name='beitrag_stufe_waehlbar')],
            },
        ),
        migrations.CreateModel(
            name='Einwilligung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.CharField(choices=[('volljaehrig', '18+ bestätigt'), ('nutzungsbedingungen', 'Nutzungsbedingungen'), ('datenschutz', 'Datenschutzerklärung'), ('ki_auswertung', 'KI-Auswertung von Profil und Beiträgen fürs Matching')], max_length=24)),
                ('version', models.CharField(help_text='Fassung des Textes, dem zugestimmt wurde', max_length=20)),
                ('erteilt_am', models.DateTimeField(default=django.utils.timezone.now)),
                ('widerrufen_am', models.DateTimeField(blank=True, null=True)),
                ('nutzer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='einwilligungen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Einwilligung',
                'verbose_name_plural': 'Einwilligungen',
                'ordering': ['-erteilt_am'],
                'constraints': [models.CheckConstraint(condition=models.Q(('widerrufen_am__isnull', True), ('widerrufen_am__gte', models.F('erteilt_am')), _connector='OR'), name='einwilligung_widerruf_nach_erteilung')],
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daumen', models.JSONField(blank=True, default=dict, help_text='Sorte 1: {dimension: true|false}')),
                ('urteil', models.CharField(blank=True, choices=[('ridebuddy', 'Ridebuddy'), ('gerne_wieder', 'gerne wieder'), ('war_nix', 'war nix')], help_text='Sorte 2', max_length=14)),
                ('erstellt', models.DateTimeField(default=django.utils.timezone.now)),
                ('ausfahrt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='kern.ausfahrt')),
                ('bewerteter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('verfasser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_verfasst', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Feedback',
                'verbose_name_plural': 'Feedback',
                'constraints': [models.UniqueConstraint(fields=('ausfahrt', 'verfasser', 'bewerteter'), name='feedback_einmal_je_paar_und_ausfahrt'), models.CheckConstraint(condition=models.Q(('verfasser', models.F('bewerteter')), _negated=True), name='feedback_nicht_ueber_sich_selbst')],
            },
        ),
        migrations.AddConstraint(
            model_name='mitgliedschaft',
            constraint=models.UniqueConstraint(fields=('crew', 'nutzer'), name='mitgliedschaft_einmal'),
        ),
        migrations.AddConstraint(
            model_name='nachricht',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('crew__isnull', True), ('empfaenger__isnull', False)), models.Q(('crew__isnull', False), ('empfaenger__isnull', True)), _connector='OR'), name='nachricht_direkt_oder_crew'),
        ),
        migrations.AddConstraint(
            model_name='teilnahme',
            constraint=models.UniqueConstraint(fields=('ausfahrt', 'nutzer'), name='teilnahme_einmal'),
        ),
        migrations.AddConstraint(
            model_name='teilung',
            constraint=models.UniqueConstraint(fields=('fremdprofil', 'empfaenger'), name='teilung_einmal_je_empfaenger'),
        ),
        migrations.AddConstraint(
            model_name='termin',
            constraint=models.CheckConstraint(condition=models.Q(('bis_datum__isnull', True), ('bis_datum__gte', models.F('datum')), _connector='OR'), name='termin_bis_nach_von'),
        ),
        migrations.AddConstraint(
            model_name='verbindung',
            constraint=models.CheckConstraint(condition=models.Q(('nutzer_a__lt', models.F('nutzer_b'))), name='verbindung_paar_geordnet'),
        ),
        migrations.AddConstraint(
            model_name='verbindung',
            constraint=models.CheckConstraint(condition=models.Q(('erreicht__gte', 2), ('erreicht__lte', 3)), name='verbindung_erreicht_2_oder_3'),
        ),
        migrations.AddConstraint(
            model_name='verbindung',
            constraint=models.CheckConstraint(condition=models.Q(('gewaehrt_a__gte', 2), ('gewaehrt_a__lte', models.F('erreicht'))), name='verbindung_gewaehrt_a_bis_erreicht'),
        ),
        migrations.AddConstraint(
            model_name='verbindung',
            constraint=models.CheckConstraint(condition=models.Q(('gewaehrt_b__gte', 2), ('gewaehrt_b__lte', models.F('erreicht'))), name='verbindung_gewaehrt_b_bis_erreicht'),
        ),
        migrations.AddConstraint(
            model_name='verbindung',
            constraint=models.UniqueConstraint(condition=models.Q(('beendet_am__isnull', True)), fields=('nutzer_a', 'nutzer_b'), name='verbindung_ein_aktives_paar'),
        ),
        migrations.AddConstraint(
            model_name='ridebuddyanfrage',
            constraint=models.CheckConstraint(condition=models.Q(('absender', models.F('empfaenger')), _negated=True), name='ridebuddy_anfrage_nicht_an_sich_selbst'),
        ),
        migrations.AddConstraint(
            model_name='ridebuddyanfrage',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'offen')), fields=('verbindung',), name='ridebuddy_anfrage_eine_offene_je_verbindung'),
        ),
        migrations.AddConstraint(
            model_name='verfuegbarkeit',
            constraint=models.UniqueConstraint(condition=models.Q(('ausfahrt__isnull', False)), fields=('nutzer', 'ausfahrt', 'datum', 'tageszeit'), name='verfuegbarkeit_einmal_je_ausfahrt'),
        ),
        migrations.AddConstraint(
            model_name='verfuegbarkeit',
            constraint=models.UniqueConstraint(condition=models.Q(('ausfahrt__isnull', True)), fields=('nutzer', 'datum', 'tageszeit'), name='verfuegbarkeit_einmal_allgemein'),
        ),
        migrations.AddConstraint(
            model_name='verfuegbarkeitszeitraum',
            constraint=models.CheckConstraint(condition=models.Q(('bis__gte', models.F('von'))), name='zeitraum_bis_nach_von'),
        ),
        migrations.AddConstraint(
            model_name='vorschlag',
            constraint=models.UniqueConstraint(fields=('empfaenger', 'kandidat', 'runde'), name='vorschlag_einmal_je_runde'),
        ),
        migrations.AddConstraint(
            model_name='vorschlag',
            constraint=models.CheckConstraint(condition=models.Q(('empfaenger', models.F('kandidat')), _negated=True), name='vorschlag_nicht_an_sich_selbst'),
        ),
    ]
