# Generated by Django 6.1.1 on 2026-09-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kern', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='breitengrad',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Nur fürs Matching und den Inhaber – nie für andere sichtbar.', max_digits=7, null=True, verbose_name='Breitengrad'),
        ),
        migrations.AddField(
            model_name='profil',
            name='laengengrad',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Nur fürs Matching und den Inhaber – nie für andere sichtbar.', max_digits=7, null=True, verbose_name='Längengrad'),
        ),
        migrations.AddConstraint(
            model_name='profil',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('breitengrad__isnull', True), ('laengengrad__isnull', True)), models.Q(('breitengrad__isnull', False), ('laengengrad__isnull', False)), _connector='OR'), name='profil_koordinaten_beide_oder_keine'),
        ),
        migrations.AddConstraint(
            model_name='profil',
            constraint=models.CheckConstraint(condition=models.Q(('breitengrad__isnull', True), models.Q(('breitengrad__gte', -90), ('breitengrad__lte', 90)), _connector='OR'), name='profil_breitengrad_im_bereich'),
        ),
        migrations.AddConstraint(
            model_name='profil',
            constraint=models.CheckConstraint(condition=models.Q(('laengengrad__isnull', True), models.Q(('laengengrad__gte', -180), ('laengengrad__lte', 180)), _connector='OR'), name='profil_laengengrad_im_bereich'),
        ),
    ]
