# Generated by Django 6.1.1 on 2026-09-25 05:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kern', '0002_profil_koordinaten'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerkmalUrteil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('region', 'Region und Radius'), ('geschlechtspraeferenz', 'Geschlechtspräferenz'), ('alterswunsch', 'Altersbereich-Wunsch'), ('verfuegbarkeit', 'Verfügbarkeit'), ('fahrart', 'Fahrart'), ('tempo', 'Tempo'), ('erfahrung', 'Erfahrung'), ('tourenformat', 'Tourenformat'), ('unterwegs', 'Unterwegs (Streckenfresser/Genießer, Übernachtung, Gruppe)'), ('themen', 'Themen'), ('sicherheit', 'Sicherheit'), ('motorrad', 'Motorrad'), ('nogo', 'No-Go'), ('stimmung', 'Stimmung')], max_length=24)),
                ('merkmal', models.CharField(help_text='Profilfeld, z. B. tempo', max_length=32)),
                ('auspraegung', models.CharField(help_text='Wert beim Gegenüber', max_length=32)),
                ('schluessel', models.CharField(help_text='SHA-256 über Zustand und Frage', max_length=64)),
                ('anbieter', models.CharField(max_length=16)),
                ('modell', models.CharField(max_length=80)),
                ('wert', models.FloatField(help_text='Wahrscheinlichkeit für „verstößt“')),
                ('vertrauen', models.FloatField()),
                ('tokens_ein', models.PositiveIntegerField(default=0)),
                ('tokens_aus', models.PositiveIntegerField(default=0)),
                ('geholt', models.DateTimeField(default=django.utils.timezone.now)),
                ('nutzer', models.ForeignKey(help_text='dessen No-Go', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Merkmal-Urteil',
                'verbose_name_plural': 'Merkmal-Urteile',
                'constraints': [models.UniqueConstraint(fields=('nutzer', 'dimension', 'merkmal', 'auspraegung'), name='merkmalurteil_einmal_je_auspraegung')],
            },
        ),
        migrations.CreateModel(
            name='PaarUrteil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('region', 'Region und Radius'), ('geschlechtspraeferenz', 'Geschlechtspräferenz'), ('alterswunsch', 'Altersbereich-Wunsch'), ('verfuegbarkeit', 'Verfügbarkeit'), ('fahrart', 'Fahrart'), ('tempo', 'Tempo'), ('erfahrung', 'Erfahrung'), ('tourenformat', 'Tourenformat'), ('unterwegs', 'Unterwegs (Streckenfresser/Genießer, Übernachtung, Gruppe)'), ('themen', 'Themen'), ('sicherheit', 'Sicherheit'), ('motorrad', 'Motorrad'), ('nogo', 'No-Go'), ('stimmung', 'Stimmung')], max_length=24)),
                ('schluessel', models.CharField(help_text='SHA-256 über Zustand und Frage', max_length=64)),
                ('anbieter', models.CharField(max_length=16)),
                ('modell', models.CharField(max_length=80)),
                ('wert', models.FloatField(help_text='Noul: Wahrscheinlichkeit für „ja“ (Konflikt)')),
                ('vertrauen', models.FloatField()),
                ('tokens_ein', models.PositiveIntegerField(default=0)),
                ('tokens_aus', models.PositiveIntegerField(default=0)),
                ('dauer_ms', models.PositiveIntegerField(default=0)),
                ('geholt', models.DateTimeField(default=django.utils.timezone.now)),
                ('gegenueber', models.ForeignKey(help_text='dessen Profil daran gemessen wird', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('urheber', models.ForeignKey(help_text='dessen Maßstab (No-Go)', on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Paar-Urteil',
                'verbose_name_plural': 'Paar-Urteile',
                'constraints': [models.UniqueConstraint(fields=('urheber', 'gegenueber', 'dimension'), name='paarurteil_einmal_je_richtung_und_dimension'), models.CheckConstraint(condition=models.Q(('urheber', models.F('gegenueber')), _negated=True), name='paarurteil_nicht_ueber_sich_selbst')],
            },
        ),
    ]
